[branches]
base = "main"
release = "release"

[tags]
chore = "Chores"
feat = "New Features"
fix = "Bug Fixes"
perf = "Performance Improvements"
refactor = "Refactors"

[packages."@semifold/docs"]
path = "docs"
resolver = "nodejs"

[packages.semifold]
path = "crates/semifold"
resolver = "rust"
assets = ["target/release/semifold"]

[packages.semifold-changelog]
path = "crates/changelog"
resolver = "rust"

[packages.semifold-resolver]
path = "crates/resolver"
resolver = "rust"

[resolver.rust.pre-check]
url = "https://crates.io/api/v1/crates/{{ package.name }}/{{ package.version }}"

[resolver.rust.pre-check.extra-headers]
User-Agent = "Semifold 0.2.0"

[[resolver.rust.prepublish]]
command = "cargo"
args = ["build", "--release"]

[[resolver.rust.publish]]
command = "cargo"
args = ["publish"]

[[resolver.rust.post-version]]
command = "cargo"
args = ["generate-lockfile"]
dry_run = true

[resolver.nodejs.pre-check]
url = "https://registry.npmjs.org/{{ package.name }}/{{ package.version }}"
