name: Semifold CI
on:
  push:
    branches: [main]

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  BINARY_NAME: semifold

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build - ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: semifold-linux-x86_64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: semifold-linux-arm64
          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: semifold-macos-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: semifold-macos-arm64
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            arch: x64
            artifact_name: semifold-windows-x86_64.exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            arch: arm64
            artifact_name: semifold-windows-arm64.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          key: build-${{ matrix.target }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Zig (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: mlugg/setup-zig@v2
      - name: Setup Zigbuild (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip3 install cargo-zigbuild
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with cargo-zigbuild (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cargo zigbuild --release --target ${{ matrix.target }}
      - name: Build
        if: matrix.os != 'ubuntu-latest'
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/semifold${{ matrix.target == 'x86_64-pc-windows-msvc' || matrix.target == 'aarch64-pc-windows-msvc' && '.exe' || '' }}
          retention-days: 7

  release:
    name: Version or Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts/
      - name: Semifold CI
        run: cargo run --bin semifold ci --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
